SELECT DISTINCT SOURCE_SYSTEM, FISCAL_YEAR, TRANSACTION_TYPE 
  FROM SIQP_TRANS_DTL
  WHERE 
  (
    (
      SOURCE_SYSTEM IN ('ERP')
      AND
      FISCAL_YEAR IN ('2023', '2024')
    )
    OR
      BATCH_OUT_ID IN ('SIQP_GRS_24102611','SIQP_POS_24102605')
  )